/*
 * This source file was generated by the Gradle 'init' task
 */

package com.pantrylogger;

class PantryLoggerBackendTest {
    // @Test void testGetMessage() {
    //     assertEquals("Hello World!", MessageUtils.getMessage());
    // }
}