### Login
POST http://localhost:8081/realms/pantry-logger/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = pantry-logger &
grant_type = password &
username = thebasikducky &
password = testing

> {%
    client.global.set("auth_token", response.body.access_token);
%}

###

### Get all ingredients
GET http://localhost:8080/ingredients
Accept: application/json
Authorization: Bearer {{auth_token}}

###

### Create a new ingredient with too short name
POST http://localhost:8080/ingredients
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "T",
    "description": "Fresh red tomato"
}

###

### Create a new ingredient and capture UUID
POST http://localhost:8080/ingredients
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Tomato",
    "description": "Fresh red tomato"
}

> {%
    client.global.set("ingredientUuid", response.body.uuid)
%}

###

### Get all ingredients
GET http://localhost:8080/ingredients
Accept: application/json
Authorization: Bearer {{auth_token}}

###

### Get ingredient by UUID (captured from POST)
GET http://localhost:8080/ingredients/{{ingredientUuid}}
Accept: application/json
Authorization: Bearer {{auth_token}}

###

### Update ingredient by UUID (captured from POST)
PATCH http://localhost:8080/ingredients/{{ingredientUuid}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Cherry Tomato",
    "description": "Small sweet tomato"
}

### Get ingredient by UUID after Patch (captured from POST)
GET http://localhost:8080/ingredients/{{ingredientUuid}}
Accept: application/json
Authorization: Bearer {{auth_token}}

###