logging:
    level:
        com.pantrylogger:
            ROOT: ${LOGGING_LEVEL:TRACE}
management:
    health:
        probes:
            enabled: true
spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDB}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: never
            platform: postgres

    jpa:
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO}
            show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect