/*
 * This source file was generated by the Gradle 'init' task
 */

package com.pantrylogger;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PantryLoggerBackend {

    public static void main(String[] args) {

        SpringApplication.run(PantryLoggerBackend.class);
    }
}