/*
 * This source file was generated by the Gradle 'init' task
 */
package com.pantrylogger.backend;

import static com.pantrylogger.backend.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}
