/*
 * This source file was generated by the Gradle 'init' task
 */
package com.pantrylogger.backend;

class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
}
